### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by guhijo** [Haacked/haacked.com#228] opened 2015-12-02 21:38 UTC
http://haacked.com/code/CustomValidationAttributeDemo.zip

**Comment by Haacked** [comment] 2015-12-02 21:42
Where'd you find the link to this?

**Comment by guhijo** [comment] 2015-12-02 22:11
http://haacked.com/archive/2009/12/07/localizing-aspnetmvc-validation.aspx/

**Comment by Haacked** [comment] 2017-09-24 16:47
Dupe of #159

**Closed by Haacked** 2017-09-24 16:47 UTC
