### ISSUE TITLE
Broken link to http://haacked.com/tags/Routing/default.aspx

### ISSUE THREAD

**Issue by danjagnow** [Haacked/haacked.com#253] opened 2016-05-12 20:37 UTC
http://haacked.com/archive/2011/01/30/introducing-routemagic.aspx/ contains a link to 
http://haacked.com/tags/Routing/default.aspx.  It asked me to log an issue, so I'm complying.

**Comment by Haacked** [comment] 2017-09-24 16:43
Yeah, all my tag posts are broken. Closing as a dupe of #71

**Closed by Haacked** 2017-09-24 16:43 UTC
